
package com.company.kegelapp.ui;

import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.NumberField;
import com.vaadin.flow.router.Route;


@Route("TeamSpielErstellen")
public class TeamSpielErstellen extends VerticalLayout
{
	
	/**
	 *
	 */
	public TeamSpielErstellen()
	{
		super();
		this.initUI();
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.h1               = new H1();
		this.horizontalLayout = new HorizontalLayout();
		this.verticalLayout   = new VerticalLayout();
		this.label            = new Label();
		this.numberField      = new NumberField();
		
		this.h1.setText("Teamspiel erstellen");
		this.label.setText("Wie viele Teams?");
		
		this.label.setSizeUndefined();
		this.numberField.setSizeUndefined();
		this.verticalLayout.add(this.label, this.numberField);
		this.verticalLayout.setSizeUndefined();
		this.horizontalLayout.add(this.verticalLayout);
		this.h1.setSizeUndefined();
		this.horizontalLayout.setSizeUndefined();
		this.add(this.h1, this.horizontalLayout);
		this.setHorizontalComponentAlignment(FlexComponent.Alignment.CENTER, this.h1);
		this.setHorizontalComponentAlignment(FlexComponent.Alignment.CENTER, this.horizontalLayout);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private NumberField      numberField;
	private H1               h1;
	private HorizontalLayout horizontalLayout;
	private VerticalLayout   verticalLayout;
	private Label            label;
	// </generated-code>

}
